In [1]:
import pandas as pd

df = pd.read_csv("List of Orders.csv")

df.head()

  Order ID  Order Date CustomerName           State       City
0  B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
1  B-25602  01-04-2018        Pearl     Maharashtra       Pune
2  B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal
3  B-25604  03-04-2018       Divsha       Rajasthan     Jaipur
4  B-25605  05-04-2018      Kasheen     West Bengal    Kolkata

In [2]:
df

    Order ID  Order Date CustomerName           State       City
0    B-25601  01-04-2018       Bharat         Gujarat  Ahmedabad
1    B-25602  01-04-2018        Pearl     Maharashtra       Pune
2    B-25603  03-04-2018        Jahan  Madhya Pradesh     Bhopal
3    B-25604  03-04-2018       Divsha       Rajasthan     Jaipur
4    B-25605  05-04-2018      Kasheen     West Bengal    Kolkata
..       ...         ...          ...             ...        ...
555      NaN         NaN          NaN             NaN        NaN
556      NaN         NaN          NaN             NaN        NaN
557      NaN         NaN          NaN             NaN        NaN
558      NaN         NaN          NaN             NaN        NaN
559      NaN         NaN          NaN             NaN        NaN

[560 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 560 entries, 0 to 559
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    str
 1   Order Date    500 non-null    str
 2   CustomerName  500 non-null    str
 3   State         500 non-null    str
 4   City          500 non-null    str
dtypes: str(5)
memory usage: 22.0 KB

In [4]:
df.isnull().sum()

Order ID        60
Order Date      60
CustomerName    60
State           60
City            60
dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df["City"].fillna("Unknown", inplace=True)

C:\Users\SACHIN\AppData\Local\Temp\ipykernel_18816\511678675.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["City"].fillna("Unknown", inplace=True)

0      Ahmedabad
1           Pune
2         Bhopal
3         Jaipur
4        Kolkata
         ...
495      Kolkata
496    Bangalore
497      Kashmir
498       Mumbai
499       Indore
Name: City, Length: 500, dtype: str

In [7]:
df

    Order ID  Order Date CustomerName              State       City
0    B-25601  01-04-2018       Bharat            Gujarat  Ahmedabad
1    B-25602  01-04-2018        Pearl        Maharashtra       Pune
2    B-25603  03-04-2018        Jahan     Madhya Pradesh     Bhopal
3    B-25604  03-04-2018       Divsha          Rajasthan     Jaipur
4    B-25605  05-04-2018      Kasheen        West Bengal    Kolkata
..       ...         ...          ...                ...        ...
495  B-26096  28-03-2019       Atharv        West Bengal    Kolkata
496  B-26097  28-03-2019         Vini          Karnataka  Bangalore
497  B-26098  29-03-2019        Pinky  Jammu and Kashmir    Kashmir
498  B-26099  30-03-2019       Bhishm        Maharashtra     Mumbai
499  B-26100  31-03-2019       Hitika     Madhya Pradesh     Indore

[500 rows x 5 columns]

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df

    Order ID  Order Date CustomerName              State       City
0    B-25601  01-04-2018       Bharat            Gujarat  Ahmedabad
1    B-25602  01-04-2018        Pearl        Maharashtra       Pune
2    B-25603  03-04-2018        Jahan     Madhya Pradesh     Bhopal
3    B-25604  03-04-2018       Divsha          Rajasthan     Jaipur
4    B-25605  05-04-2018      Kasheen        West Bengal    Kolkata
..       ...         ...          ...                ...        ...
495  B-26096  28-03-2019       Atharv        West Bengal    Kolkata
496  B-26097  28-03-2019         Vini          Karnataka  Bangalore
497  B-26098  29-03-2019        Pinky  Jammu and Kashmir    Kashmir
498  B-26099  30-03-2019       Bhishm        Maharashtra     Mumbai
499  B-26100  31-03-2019       Hitika     Madhya Pradesh     Indore

[500 rows x 5 columns]

In [11]:
import pandas as pd

df = pd.read_csv("List of Orders.csv")

# Convert Order Date correctly
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    dayfirst=True
)

df.head()

,Order ID,Order Date,CustomerName,State,City,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,NaN,NaN,NaN,NaN,NaN
1,B-25602,2018-04-01,Pearl,Maharashtra,Pune,NaN,NaN,NaN,NaN,NaN
2,B-25603,2018-04-03,Jahan,Madhya Pradesh,Bhopal,NaN,NaN,NaN,NaN,NaN
3,B-25604,2018-04-03,Divsha,Rajasthan,Jaipur,NaN,NaN,NaN,NaN,NaN
4,B-25605,2018-04-05,Kasheen,West Bengal,Kolkata,NaN,NaN,NaN,NaN,NaN

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      500 non-null    str
 1   Order Date    500 non-null    datetime64[us]
 2   CustomerName  500 non-null    str
 3   State         500 non-null    str
 4   City          500 non-null    str
 5   Unnamed: 5    0 non-null      float64
 6   Unnamed: 6    0 non-null      float64
 7   Unnamed: 7    0 non-null      float64
 8   Unnamed: 8    0 non-null      float64
 9   Unnamed: 9    0 non-null      float64
dtypes: datetime64[us](1), float64(5), str(4)
memory usage: 39.2 KB

In [13]:
df.dropna(subset=["Order Date"], inplace=True)

In [14]:
df["Month"] = df["Order Date"].dt.month_name()

df["Year"] = df["Order Date"].dt.year

In [15]:
df

,Order ID,Order Date,CustomerName,State,City,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Month,Year
0,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,NaN,NaN,NaN,NaN,NaN,April,2018
1,B-25602,2018-04-01,Pearl,Maharashtra,Pune,NaN,NaN,NaN,NaN,NaN,April,2018
2,B-25603,2018-04-03,Jahan,Madhya Pradesh,Bhopal,NaN,NaN,NaN,NaN,NaN,April,2018
3,B-25604,2018-04-03,Divsha,Rajasthan,Jaipur,NaN,NaN,NaN,NaN,NaN,April,2018
4,B-25605,2018-04-05,Kasheen,West Bengal,Kolkata,NaN,NaN,NaN,NaN,NaN,April,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
495,B-26096,2019-03-28,Atharv,West Bengal,Kolkata,NaN,NaN,NaN,NaN,NaN,March,2019
496,B-26097,2019-03-28,Vini,Karnataka,Bangalore,NaN,NaN,NaN,NaN,NaN,March,2019
497,B-26098,2019-03-29,Pinky,Jammu and Kashmir,Kashmir,NaN,NaN,NaN,NaN,NaN,March,2019
498,B-26099,2019-03-30,Bhishm,Maharashtra,Mumbai,NaN,NaN,NaN,NaN,NaN,March,2019
499,B-26100,2019-03-31,Hitika,Madhya Pradesh,Indore,NaN,NaN,NaN,NaN,NaN,March,2019

In [16]:
df["CustomerName"] = df["CustomerName"].str.strip()

df["State"] = df["State"].str.strip()

df["City"] = df["City"].str.strip()

In [17]:
df["CustomerName"] = df["CustomerName"].str.title()

df["State"] = df["State"].str.title()

df["City"] = df["City"].str.title()

In [18]:
df["State"].unique()

df["City"].unique()

<StringArray>
[         'Ahmedabad',               'Pune',             'Bhopal',
             'Jaipur',            'Kolkata',          'Bangalore',
            'Kashmir',            'Chennai',            'Lucknow',
              'Patna', 'Thiruvananthapuram',         'Chandigarh',
              'Simla',            'Gangtok',                'Goa',
             'Kohima',          'Hyderabad',             'Mumbai',
             'Indore',              'Surat',            'Udaipur',
          'Allahabad',           'Amritsar',              'Delhi']
Length: 24, dtype: str

In [19]:
df.to_csv("Cleaned_List_of_Orders.csv", index=False)

In [20]:
df

,Order ID,Order Date,CustomerName,State,City,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Month,Year
0,B-25601,2018-04-01,Bharat,Gujarat,Ahmedabad,NaN,NaN,NaN,NaN,NaN,April,2018
1,B-25602,2018-04-01,Pearl,Maharashtra,Pune,NaN,NaN,NaN,NaN,NaN,April,2018
2,B-25603,2018-04-03,Jahan,Madhya Pradesh,Bhopal,NaN,NaN,NaN,NaN,NaN,April,2018
3,B-25604,2018-04-03,Divsha,Rajasthan,Jaipur,NaN,NaN,NaN,NaN,NaN,April,2018
4,B-25605,2018-04-05,Kasheen,West Bengal,Kolkata,NaN,NaN,NaN,NaN,NaN,April,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
495,B-26096,2019-03-28,Atharv,West Bengal,Kolkata,NaN,NaN,NaN,NaN,NaN,March,2019
496,B-26097,2019-03-28,Vini,Karnataka,Bangalore,NaN,NaN,NaN,NaN,NaN,March,2019
497,B-26098,2019-03-29,Pinky,Jammu And Kashmir,Kashmir,NaN,NaN,NaN,NaN,NaN,March,2019
498,B-26099,2019-03-30,Bhishm,Maharashtra,Mumbai,NaN,NaN,NaN,NaN,NaN,March,2019
499,B-26100,2019-03-31,Hitika,Madhya Pradesh,Indore,NaN,NaN,NaN,NaN,NaN,March,2019